fix timeouts

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -9,11 +9,25 @@ function main {
     sleep 1
   done
 
-  ssh -o StrictHostKeyChecking=no github.com true 2>/dev/null || true
+  if [[ "$(id -u -n)" != "ubuntu" ]]; then
+    exec ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@localhost "$BASH_SOURCE" "$@"
+    return $?
+  fi
 
-  git clone git@github.com:imma/ubuntu
-  mv ubuntu/.git .
-  rm -rf ubuntu
+  if [[ "$(id -u -n)" != "ubuntu" ]]; then
+    echo "ERROR: failure to become ubuntu" 1>&2
+    return 1
+  fi
+
+  if [[ ! -d .git ]]; then
+    ssh -o StrictHostKeyChecking=no github.com true 2>/dev/null || true
+
+    git clone git@github.com:imma/ubuntu
+    mv ubuntu/.git .
+    rm -rf ubuntu
+  fi
+
+  git fetch
   git reset --hard
   git pull
 
